server {
    listen 443 ssl;
    server_name central;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    location /api/extensions/scannerdefinitions {
        alias /data/vulnerabilities.zip;
        default_type application/zip;
    }

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
